
server:
    port: 8081

spring:
    cloud:
        config:
            server:
                git:
                    default-label: multiple-instances
                    uri: https://github.com/m44rx/microservices-tutorial-master
                    search-paths: config-data
    application: 
        name: config-service

